name: Java Code Check
on: pull_request

jobs:
  checkstyle_job:
    runs-on: custom-runner
    name: Checkstyle Job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: error
          fail_on_error: true
          filter_mode: nofilter

  tests_job:
    runs-on: custom-runner
    name: Tests Job
    container:
      image: 127322177288.dkr.ecr.us-west-1.amazonaws.com/cb-image:latest
      credentials:
        username: AWS
        password: ${{ secrets.AWS_ECR_PASSWORD }}
    services:
      mysql-test:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots test
