name: Java Code Check
on: pull_request

jobs:
  checkstyle_job:
    runs-on: custom-runner
    name: Checkstyle Job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: error
          fail_on_error: true
          filter_mode: nofilter

  tests_job:
    runs-on: custom-runner
    name: Tests Job
    container:
      image: 127322177288.dkr.ecr.us-west-1.amazonaws.com/cb-image:latest
      credentials:
        username: AWS
        password: ${{ secrets.AWS_ECR_PASSWORD }}
    services:
      mysql:
        image: mysql/mysql-server
        ports:
          - 3306:3306
        options: -e MYSQL_ROOT_PASSWORD=root -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots test
  tests_job_2:
    runs-on: custom-runner
    name: Tests Job 2
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Set up MySQL DB
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: root # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql database: test
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots test
