name: Java Code Check
on: pull_request

jobs:
  tests_job:
    runs-on: ubuntu-latest
    name: Tests Job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Set up MySQL DB
        uses: mirromutth/mysql-action@v1.1
        with:
            mysql root password: root # Required if "mysql user" is empty, default is empty. The root superuser password
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots test
